web/apps/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
]

web/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls", namespace="core")),
]

web/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager


class UserAccountManager(UserManager):
    pass


class UserAccount(AbstractUser):
    objects = UserAccountManager()

web/apps/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import UserAccount


class UserAccountCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = UserAccount


class UserAccountChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = UserAccount

web/apps/core/views.py
from django.views import generic


class HomePage(generic.TemplateView):
    template_name = "core/index.html"

web/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %} - Sussurros</title>
    {# ===== Favicons ===== #}
    <link rel="shortcut icon" href="https://res.cloudinary.com/dejjtt8yt/image/upload/v1672073964/djemplate/favicon_f0mvsy.ico" type="image/x-icon">
    {# ===== Bootstrap CSS ===== #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {# ===== Font Awesome ===== #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {# ===== Static CSS ===== #}
    <link rel="stylesheet" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}">
    {# ===== Bootstrap JS ===== #}
    <script deref src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script deref src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    {# ===== Static JS ===== #}
    <script deref src="{% block script %}{% static "js/script.js" %}{% endblock script %}"></script>
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

web/templates/core/base_core.html
{% extends 'base.html' %}

{% block title %}{% block subtitle %}{% endblock subtitle %} / Sussurros{% endblock title %}

{% block content %}

{# === HEADERD ===#}
<header>
  <div class=" container-lg">
    <div class="d-flex justify-content-between align-items-center">

      <div class="btn-group" role="group" aria-label="Basic example">
        <button class="btn" data-bs-toggle="modal" data-bs-target="#ModalSearch">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>

        <button class="btn d-none d-md-block" data-bs-toggle="modal" data-bs-target="#ModalNewletter">
          Newsletter
        </button>
      </div>

      <h1 class="m-0">
        <a href="{% url 'core:index' %}" class="btn text-decoration-none fs-1">
          Sussurros
        </a>
      </h1>

      <div class="btn-group d-none d-md-block" role="group" aria-label="Basic example">
        <a href="" class="btn">
          <i class="fa-brands fa-facebook"></i>
        </a>
        <a href="" class="btn">
          <i class="fa-brands fa-twitter"></i>
        </a>
        <a href="" class="btn">
          <i class="fa-brands fa-instagram"></i>
        </a>
      </div>

      <button class="btn d-md-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#MenuOffCanvvas"
        aria-controls="MenuOffCanvvas">
        <i class="fa-solid fa-bars"></i>
      </button>

    </div>
  </div>
</header>

{% block core_content %}{% endblock core_content %}

<footer class="py-4">
  <div class="container-lg">
    <p class="m-0 text-capitalize text-dark fs-6">Sussurros - 2023</p>
  </div>
</footer>

{# Modal Search #}
<div class="modal fade" id="ModalSearch" tabindex="-1" aria-labelledby="ModalSearchLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content" <div class="modal-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search Here..." aria-label="Recipient's username"
            aria-describedby="basic-addon2">
          <button type="submit" class="input-group-text">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>

{# Modal Newsletter #}
<div class="modal fade" id="ModalNewletter" tabindex="-1" aria-labelledby="ModalNewletterLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content" <div class="modal-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group">
          <input type="email" class="form-control" placeholder="What is your email" aria-label="Recipient's username"
            aria-describedby="basic-addon2">
          <button type="submit" class="input-group-text">
            subscribe
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>

{# Menu OffCanvas #}
<div class="offcanvas offcanvas-end" tabindex="-1" id="MenuOffCanvvas" aria-labelledby="MenuOffCanvvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="MenuOffCanvvasLabel">Sussurros</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <p>Sussurrando</p>
  </div>
</div>

{% endblock content %}

web/templates/core/index.html
{% extends 'core/base_core.html' %}

{% block subtitle %}Home{% endblock subtitle %}

{% block core_content %}
{% endblock core_content %}