blogango/apps/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path(
        "",
        views.ArticleList.as_view(),
        name="article_list",
    ),
    path(
        "tag/<slug:tag_slug>/",
        views.ArticleList.as_view(),
        name="article_list_by_tag",
    ),
    path(
        "articles/<int:year>/<int:month>/<int:day>/<slug:article_slug>/",
        views.ArticleDetail.as_view(),
        name="article_detail",
    ),
    path(
        (
            "tag/<slug:tag_slug>/"
            "articles/<int:year>/<int:month>/<int:day>/<slug:article_slug>/"
        ),
        views.ArticleDetail.as_view(),
        name="article_detail_by_tag",
    ),
]

blogango/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.articles.urls", namespace="articles")),
]

blogango/apps/articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext as _
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager


class ArticleManager(models.Manager):
    def published(self):
        queryset = super().get_queryset().defer("created", "modified")
        return queryset.filter(status=self.model.Status.PUBLISHED)


class Article(TimeStampedModel):
    class Status(models.TextChoices):
        DRAFT = 0, _("draft")
        PUBLISHED = 1, _("published")

    title = models.CharField(_("title"), max_length=250)
    slug = models.SlugField(_("slug"), max_length=250, unique_for_date="published")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_("author"),
    )
    body = models.TextField(_("body"))
    status = models.CharField(
        _("status"), max_length=1, choices=Status.choices, default=Status.DRAFT
    )
    published = models.DateTimeField(_("published"), default=timezone.now)
    tags = TaggableManager(_("tags"), blank=True)

    objects = ArticleManager()

    class Meta:
        verbose_name = _("article")
        verbose_name_plural = _("articles")
        ordering = ("-published",)

        indexes = [models.Index(fields=["-published"])]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        datas = {
            "year": self.published.year,
            "month": self.published.month,
            "day": self.published.day,
            "article_slug": self.slug,
        }

        return reverse("articles:article_detail", kwargs=datas)

blogango/apps/articles/views.py
from django.shortcuts import get_object_or_404

from .mixins import BaseArticleDetailView, BaseArticleListView, TagMixin


class ArticleList(TagMixin, BaseArticleListView):
    paginate_by = 10

    def get_queryset(self):
        self.tag = self.get_tag()
        queryset = super().get_queryset()

        if self.tag:
            queryset = queryset.filter(tags__in=[self.tag])

        return queryset


class ArticleDetail(TagMixin, BaseArticleDetailView):
    def get_object(self):
        self.object = get_object_or_404(
            self.queryset,
            published__year=self.kwargs.get("year"),
            published__month=self.kwargs.get("month"),
            published__day=self.kwargs.get("day"),
            slug=self.kwargs.get("article_slug"),
        )

        return self.object

blogango/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block title %}
Article: {{ object.title }}
{% endblock title %}

{% block header %}
{{ object.title }}
{% endblock header %}

{% block content %}
  {% include "../includes/article.html" with detail=True %}
{% endblock content %}

blogango/templates/articles/article_list.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
  {% for object in object_list %}
    {% if tag %}
      {% with object.published as op %}
        <a class="text-decoration-none text-dark"
           href="{% url 'articles:article_detail_by_tag' tag_slug=tag.slug year=op.year month=op.month day=op.day article_slug=object.slug %}"
        >
          {% include "../includes/article.html" %}
        </a>
        {% endwith %}
    {% else %}
      <a class="text-decoration-none text-dark" href="{{ object.get_absolute_url}}">
        {% include "../includes/article.html" %}
      </a>
    {% endif %}
  {% empty%}
    <p class="alert alert-secondary">There are no published articles yet</p>
  {% endfor %}
  {% include "../includes/pagination.html" %}
{% endblock content %}

blogango/templates/base.html
{% load i18n static %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %} - Blogango</title>
    {# ===== Favicons ===== #}
    <link rel="shortcut icon" href="https://res.cloudinary.com/dejjtt8yt/image/upload/v1672073964/djemplate/favicon_f0mvsy.ico" type="image/x-icon">
    {# ===== Bootstrap CSS ===== #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {# ===== Font Awesome ===== #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {# ===== Bootstrap JS ===== #}
    <script deref src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script deref src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    {# ===== STATIC CSS ===== #}
    {% block stylesheet %} {% endblock stylesheet %}
  </head>
  <body class="">

    <div class="container-lg">

      {% include "includes/breadcrumb.html" %}

      <header>
        <div class="container-lg">
          <h1 class="text-capitalize text-dark text-center fs-1">
            {% block header %}Blogango{% endblock header %}
          </h1>
        </div>
      </header>


      <div class="row">
        <main class="col-12 col-md-7 col-lg-8">
          {% block content %} {% endblock content %}
        </main>
        <aside class="col border-start">
          {% include "includes/about.html"%}
        </aside>
      </div>
    </div>

  </body>
</html>

blogango/templates/includes/about.html
<section class="mb-3">
  <main class="px-3">
    <h5 class="mb-3 border-bottom border-primary">About</h5>
    <p>This blog is my first project with Django. being part of my studies with the book Django 4 by examples of Antonio Melé. </p>
    <p>To learn more about this project, visit the repository at <a class="btn btn-link" href="">GitHub</a>.</p>
  </main>
</section>

blogango/templates/includes/article.html
<article class="mb-3 pb-3 border-bottom">
  <p class="fst-italic text-secondary fs-6">Published at {{ object.published|date:"SHORT_DATE_FORMAT"}} by {{ object.author|capfirst }}</p>
  {% if not detail %}
    <h3 class="fs-3 text-dark">{{ object.title }}</h3>
    <div>{{ object.body|truncatewords:32|linebreaks }}</div>
  {% else %}
    <div>{{ object.body|linebreaks }}</div>
  {% endif %}
  <div class="">
    {% for tag in object.tags.all %}
    <a class="btn btn-link" href="{% url 'articles:article_list_by_tag' tag_slug=tag.slug %}">
      {{ tag.name }}
    </a>
    {% endfor %}
  </div>
</article>

blogango/templates/includes/breadcrumb.html
<!-- breadcrumb -->
<div class="sticky-top bg-white py-3 d-none d-md-block">
  <nav class="" aria-label="breadcrumb">
    <ol class="breadcrumb m-0">

      {% if not object and not tag %}
      <li class="breadcrumb-item active" aria-current="page">Home</li>
      {% else %}
      <li class="breadcrumb-item"><a href="{% url 'articles:article_list' %}">Home</a></li>
      {% endif %}

      {% if not object and tag %}
      <li class="breadcrumb-item active" aria-current="page">tag: {{ tag.name }}</li>
      {% elif object and tag %}
      <li class="breadcrumb-item"><a href="{% url 'articles:article_list_by_tag' tag_slug=tag.slug %}">tag: {{ tag.name }}</a></li>
      {% endif %}

      {% if object %}
      <li class="breadcrumb-item active" aria-current="page">article: {{ object.title|truncatechars:16 }}</li>
      {% endif %}

    </ol>
  </nav>
</div>

blogango/templates/includes/pagination.html
{% if is_paginated %}
  <nav aria-label="Pagination">
    <ul class="pagination pagination-sm justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <i class="fa-solid fa-angle-left"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <i class="fa-solid fa-angle-left"></i>
          </span>
        </li>
      {% endif %}
      {% for page in paginator.page_range %}
        {% if page == 1  or page == page_obj.paginator.num_pages %}
          {% if page_obj.number == page %}
            <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% endif %}
        {% else%}
          {% if page_obj.number == page %}
            <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% elif page > page_obj.number|add:'-4' and page < page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% elif page == page_obj.number|add:'-4' or page == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}
        {% endif%}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <i class="fa-solid fa-angle-right"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <i class="fa-solid fa-angle-right"></i>
          </span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

blogango/templates/includes/tag_list.html
{% for tag in object.tags.all %}
<a class="btn btn-sm btn-outline-secondary" href="{% url 'articles:article_list_by_tag' tag_slug=tag.slug %}">{{ tag.name }}</a>
{% endfor %}