project/apps/articles/urls.py
""" URLs settings """

from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.articles_list, name="list"),
    path(
        "article/<int:year>/<int:month>/<int:day>/<slug:article_slug>/",
        views.articles_detail,
        name="detail",
    ),
]

project/apps/articles/models.py
"""Articles Model"""

from typing import Self

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext as _
from taggit.managers import TaggableManager


class TimeStampedModel(models.Model):
    created = models.DateTimeField(_("created"), auto_now_add=True)
    modified = models.DateTimeField(_("modified"), auto_now=True)

    class Meta:
        abstract = True


class Article(TimeStampedModel):
    class Status(models.TextChoices):
        DRAFT = 0, _("draft")
        PUBLISHED_AND_AVAILABLE = 1, _("published and available")
        PUBLISHED_AND_UNVAILABLE = 2, _("published and unavailable")

    title = models.CharField(_("title"), max_length=250)
    slug = models.SlugField(_("slug"), max_length=250, unique_for_date="published")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_("author")
    )
    body = models.TextField(_("body"))
    status = models.CharField(
        _("status"), max_length=1, choices=Status.choices, default=Status.DRAFT
    )

    published = models.DateTimeField(_("published"), default=timezone.now)

    tags = TaggableManager(_("tags"), blank=True)

    class Meta:
        verbose_name = _("article")
        verbose_name_plural = _("articles")
        ordering = ("-published",)

        indexes = [models.Index(fields=["-published"])]

    def __str__(self) -> str:
        return str(self.title)

    def save(self, *args, **kwargs) -> Self:
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        datas = {
            "year": self.published.year,
            "month": self.published.month,
            "day": self.published.day,
            "article_slug": self.slug,
        }

        return reverse("articles:detail", kwargs=datas)

project/apps/articles/views.py
""" View settings """

from django.shortcuts import get_object_or_404
from django.views import generic

from .mixins import ArticleMixin
from .models import Article


class ArticleList(ArticleMixin, generic.ListView):
    paginate_by = 10


articles_list = ArticleList.as_view()


class ArticleDetail(ArticleMixin, generic.DetailView):
    def get_object(self) -> Article:
        self.object = get_object_or_404(
            self.get_queryset(),
            published__year=self.kwargs.get("year"),
            published__month=self.kwargs.get("month"),
            published__day=self.kwargs.get("day"),
            slug=self.kwargs.get("article_slug"),
        )

        return self.object


articles_detail = ArticleDetail.as_view()

project/templates/articles/article_detail.html
{% extends "base.html" %}

{% block title %}
Article: {{ object.title}}
{% endblock title %}

{% block header %}
{{ object.title }}
{% endblock header %}

{% block content %}
<article class="mb-3 card border-0">
  <div class="card-body">
    <p class="text-secondary fst-italic fs-6">Publication at {{ object.published|date:"SHORT_DATE_FORMAT" }} by {{ object.author|capfirst }}</p>
    <div>
      {{ object.body|linebreaks }}
    </div>
    {% for tag in object.tags.all %}
      <span class="btn btn-outline-danger btn-sm">
        {{ tag.name}}
      </span>
    {% endfor %}
  </div>
</article>
{% endblock content %}

project/templates/articles/article_list.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}
  {% for object in object_list %}
    <article class="py-2 mb-3 border-bottom">
      <h3><a class="text-dark" href="{% url 'articles:detail' pk=object.pk %}">
          {{ object.title }}
      </a></h3>
      <p class="fst-italic fs-6 text-secondary">Published at {{ object.published|date:"SHORT_DATE_FORMAT" }} by {{ object.author }}</p>
      <div>{{ object.body|truncatewords:32|linebreaks }}</div>

      {% for tag in object.tags.all %}
      <span class="btn btn-outline-danger btn-sm">
        {{ tag.name }}
      </span>
      {% endfor %}

    </article>
  {% empty %}
  <p class="alert alert-secondary">No articles have been published yet</p>
  {% endfor %}
  {% include "../includes/pagination.html" %}
{% endblock content %}

project/templates/base.html
{% load i18n static tags %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %} - Blog Application</title>
    {# ===== Favicons ===== #}
    <link rel="shortcut icon" href="https://res.cloudinary.com/dejjtt8yt/image/upload/v1672073964/djemplate/favicon_f0mvsy.ico" type="image/x-icon">
    {# ===== Bootstrap CSS ===== #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {# ===== Font Awesome ===== #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {# ===== Bootstrap JS ===== #}
    <script deref src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script deref src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    {# ===== STATIC CSS ===== #}
    {% block stylesheet %} {% endblock stylesheet %}
  </head>
  <body class="">

    <div class="container-lg">

      {% include "includes/breadcrumb.html" %}

      <header>
        <div class="container-lg">
          <h1 class="text-capitalize text-dark text-center fs-1">
            {% block header %}blog Application{% endblock header %}
          </h1>
        </div>
      </header>


      <div class="row">
        <main class="col-12 col-md-7 col-lg-8">
          {% block content %} {% endblock content %}
        </main>
        <aside class="col">
          {% include "includes/about.html"%}
          {% tags %}
        </aside>
      </div>
    </div>

  </body>
</html>

project/templates/includes/about.html
<section class="shadow mb-3">
  <header class="p-3">
    <h5 class="pb-1 border-bottom border-danger">About</h5>
  </header>
  <main class="p-3">
    <p>This blog is my first project with Django. being part of my studies with the book Django 4 by examples of Antonio Melé. </p>
      <p>To learn more about this project, visit the repository at <a class="btn btn-link text-danger" href="https://github.com/DaniloMartoCarvalho/Blog-Application">GitHub</a>.</p>
  </main>
</section>

project/templates/includes/breadcrumb.html
<!-- breadcrumb -->
<div class="sticky-top bg-white py-3 d-none d-md-block">
  <nav class="" aria-label="breadcrumb">
    <ol class="breadcrumb m-0">
      {% if not object %}
      <li class="breadcrumb-item active" aria-current="page">Home</li>
      {% else %}
      <li class="breadcrumb-item"><a class="text-danger" href="{% url 'articles:list' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Article: {{ object.title|truncatechars:16 }}</li>
      {% endif %}
    </ol>
  </nav>
</div>

project/templates/includes/latest_article.html
<!-- === latest article === -->

project/templates/includes/pagination.html
<!-- === Pagination === -->
{% if is_paginated %}
  <nav aria-label="Pagination">
    <ul class="pagination pagination-sm justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link text-danger" href="?page={{ page_obj.previous_page_number }}">
            <i class="fa-solid fa-angle-left"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <i class="fa-solid fa-angle-left"></i>
          </span>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        {% if page == 1  or page == page_obj.paginator.num_pages %}
          {% if page_obj.number == page %}
            <li class="page-item active">
              <a class="page-link bg-danger border-danger" href="?page={{ page }}">
                {{ page }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link text-danger" href="?page={{ page }}">
                {{ page }}
              </a>
            </li>
          {% endif %}
        {% else%}
          {% if page_obj.number == page %}
            <li class="page-item active">
              <a class="page-link bg-danger border-danger" href="?page={{ page }}">
                {{ page }}
              </a>
            </li>
          {% elif page > page_obj.number|add:'-4' and page < page_obj.number|add:'4' %}
            <li class="page-item">
              <a class="page-link text-danger" href="?page={{ page }}">
                {{ page }}
              </a>
            </li>
          {% elif page == page_obj.number|add:'-4' or page == page_obj.number|add:'4' %}
            <li class="page-item">
              <a class="page-link text-danger" href="">
                ...
              </a>
            </li>
          {% endif %}
        {% endif%}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link text-danger" href="?page={{ page_obj.next_page_number }}">
            <i class="fa-solid fa-angle-right"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <i class="fa-solid fa-angle-right"></i>
          </span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

project/templates/includes/tags.html
{% if tags %}
<section class="shadow mb-3">
  <header class="p-3">
    <h5 class="pb-1 border-bottom border-danger">Tags</h5>
  </header>
  <main class="p-3">
    {% for tag in tags %}
     <span class="btn btn-sm btn-outline-danger">
       {{ tag.name }}
     </span>
    {% endfor %}
  </main>
</section>
{% endif %}